### ISSUE TITLE
Landing Page (HTML)

### ISSUE THREAD

**Issue by Zekvyrin** [drupalcampgr/landing2016#3]

**Comment by Zekvyrin** [comment]
First draft is done.

TODO:
Responsive
εικόνες
εφέ
css transitions
test email form
twitter
fb
mailto (verify someone is receinving email)
js time left for event

**Comment by Zekvyrin** [comment]
js fixed by AchillesKal in be7168f

**Comment by KostasBlank** [comment]
I did some reworking on images for the content slice in bd23f5f78c61b00f0c206953e63ad2606b904fc8. The header slice needs to be split to more images for better responsive handling.

**Comment by KostasBlank** [comment]
The current todo list:
Responsive (release blocker)
εφέ
css transitions
test email form (release blocker)
mailto (verify someone is receiving email) (release blocker)

**Comment by Zekvyrin** [comment]
i think we're ok with most things.. 

any additions are of course welcomed.
